version: "3.3"

services:
  backend:
    container_name: tts_dev
    image: dev/tts
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_ENV=xx
    ports:
      - "8000:8000"
    volumes:
      - .:/app
